# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - bash: sudo mkdir -p /usr/local/squid
  - bash: sudo ls -l /usr/local
  - bash: sudo chmod -R +rwx /usr/local/
  - bash: touch /usr/local/squid/test.txt
  - bash: echo 'test' > /usr/local/squid/test.txt
# - bash: sudo apt install automake -y & sudo apt install build-essential libtool -y & sudo apt install libtool -y & sudo apt install libtool-bin -y
#   displayName: Install requirements

# - bash: autoreconf --install
#   displayName: Run autoreconf
# - bash: automake
#   displayName: Run automake
# - bash: mkdir squid-proxy
# - script: |
#     ./configure --prefix='$(LOCATION)'

# - script: |
#     make all
#   displayName: make - build project

# - script: |
#     make install
#   displayName: make - install project in squid-proxy
# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(LOCATION)'
#     targetFolder: '$(Build.ArtifactStagingDirectory)'    

# - task: PublishBuildArtifacts@1    
#   displayName: 'Publish Artifact: drop'
#   inputs:
#     PathtoPublish: '$(build.artifactstagingdirectory)'